### ISSUE TITLE
Hello! I'd like to work on your project

### ISSUE THREAD

**Issue by fruit-matrix** [Gwion/Gwion#180]
**Well, tell us what you think**

**Comment by fennecdjay** [comment]
Nice to read you here :smile:
Please accept the invitation (I'll be sending in minutes).
Remember there is no stupid question, in particular in this project where a lot of documentation is lacking, so raising question leads to more sensible/complete docs.
Cheers!

**Comment by dk4267** [comment]
Hey, I'm interested as well.

**Comment by fennecdjay** [comment]
Inviting you right now :smile:

**Comment by fennecdjay** [comment]
@dk4267, is there anything you want to discuss/point out?
I had a conversation with @fruit-matrix earlier today, it helped me figuring out some things that are still unclear about this project (yet I got to write them up).
If so, don't be shy and contact me, either on reddit or use github discussions when you've joined.
Looking forward reading you.

**Comment by amberisvibin** [comment]
Hello! I would also like to help out, if I can. I found your repo through the dev.to request for contributions. 
I have semi-moderate knowledge of c, but am willing to help out on the documentation.

**Comment by fennecdjay** [comment]
@amberisvibin that's lovely? I'm inviting you right now!

**Comment by amberisvibin** [comment]
> @amberisvibin that's lovely? I'm inviting you right now!

I've joined! How is communication done? The email list?

**Comment by fennecdjay** [comment]
I think the teams page will be enough for communication. A bit busy at the moment, but I'll find some time soon to document the documentation process. I'll let you know. Cheers!

**Comment by amberisvibin** [comment]
Thank you!

**Comment by forrcaho** [comment]
Hey, me too! I'm looking to do 2 more PRs for Hacktoberfest, and I'm familiar with ChucK -- even worked on the code a tiny bit. What's the inspiration to create a new language? How can I help?

**Comment by fennecdjay** [comment]
Hi!
 > What's the inspiration to create a new language?

At some point, chuck was not be fast enough to handle what I needed/wanted to do.
I also badly lacked function pointers and generics. So, well, I guess that's it.

I'm a bit busy today, but I'll try to update some issues.

**Comment by forrcaho** [comment]
Ok, I've got to admit, my simple edits to the README are insufficient. I
still haven't been able to make a sound from gwion.

I still really don't understand how to make sound. I'm going thru all the
plug subdirs and trying to make them individually; sometimes there are
dependencies I can apt-get or find on github or elsewhere (it took me
forever to find soundpipe; it's now at https://git.sr.ht/~pbatch/soundpipe/).
I'm still confused by some of the dependencies and not sure what to get,
but I take it if I have Modules and Jack I should be able to get some sound.

I'm trying to run these executables without installing, and maybe that's a
mistake, but I'd like to be able to run things first, and it should be
possible with the right environment. I see in plug/Modules, test.gw is a
simple file to play a SinOsc. I'm guessing that the shared libs need to be
on LD_LIBRARY_PATH, so I'm trying to run that test (from the Modules dir)
like this:

forrcaho@vortex:~/github/Gwion/plug/Modules$ LD_LIBRARY_PATH=.:../Jack
../../gwion test.gw
/home/forrcaho/github/Gwion/plug/Modules/test.gw:1:5: unknown type 'SinOsc'
var SinOsc s => dac;
while compiling file 'test.gw'

I'm assuming there's some way to get this test to work, but I'm not finding
it.

**Comment by fennecdjay** [comment]
I'm not home for the moment, but I'll try to provide pointers anyway.
You got to provide the libs directory with `-p` (there can be multiple).
And `-d` for the driver
Modules depends on Soundpipe.
So a working command should be something like:
```sh
forrcaho@vortex:~/github/Gwion/plug/Modules$ ../../gwion -p ../Jack -p ../Soundpipe -p . -d jack test.gw
```

I'm sorry for the inconvenience :confused:
The good point is that it makes it clear plug READMEs need to provide more information:
  * where to find dependencies if any
  * What is the name of driver/module if any.
Also command line usage needs to be documented.
Thank you for all that :smile: 


----
Also, congrats for findings an original an seemingly active Soundpipe repo :+1:

**Comment by forrcaho** [comment]
The soundpipe repo at Sourcehut, although it appears to be active, is for
some reason not complete. There is a version at
https://github.com/hexdump0815/soundpipe-backup which at least allowed me
to compile the Soundpipe plug successfully -- still working on getting
sound.

**Comment by fennecdjay** [comment]
Thanks for keeping me updated. It tested the jack plugin back home, was working :smile:
I'll do everything to help!
Is your jack setup OK?
Or would it help if I update the pulseaudio driver?

**Comment by forrcaho** [comment]
I succeeded in getting some sound using the command line you provided, but
instead of a sine wave it was noise. It sounded more like pink noise than
white noise to me, but I'm just using my laptop speakers so it's hard to
tell. On the bright side, the sound did seem to last five seconds as one
would expect from the code.

**Comment by fennecdjay** [comment]
> instead of a sine wave it was noise
Weird ... When you build Gwion, did you change anything in `util/config.mk' (I'm asking because this *might* come from setting `USE_DOUBLE` to 1). I never had a problem with the jack driver before, I don't know. Can you confirm jack is working normally on your machine?

**Comment by forrcaho** [comment]
Yeah, close. I had set USE_DOUBLE to 1 when I built soundpipe. (I thought I
had made the corresponding change to Gwion, but apparently not). Once I
rebuilt soundpipe not to use doubles, I got a sine wave as expected. So it
worked!

**Comment by fennecdjay** [comment]
That's great news!!! :champagne:
I (just) started porting STK, also we should soon have a chuck => gwion (and virce-versa) transpiler.

**Comment by forrcaho** [comment]
I just exchanged a bit of email with Paul Batchelor and found out that the
soundpipe repo I found on Sourcehut is a new major revision, and as such
has breaking changes. The latest sources for the version we're using are a
part of AudioKit; it looks like they're at
https://github.com/AudioKit/AudioKit/tree/v5-master/Sources/soundpipe . I
think the Gwion project my want to maintain our own soundpipe sources as a
submodule. (I also noticed sporth, it seems Gwion also uses, in a sibling
directory of the AudioKit repo, so maybe we want a submodule for that
source too?)

**Comment by fennecdjay** [comment]
Nice!
I think plugins should have a submodule if/when the library they depends on (if any) is available as a git repo.
I'm not sure whether we should maintain Soundpipe or Sporth (you're right, there's a sporth module, and it's pretty cool IMHO), I'd rather use upstream for both when we can.
But I'm open to discussion.

**Comment by fennecdjay** [comment]
@all-contributors please add @forrcaho for ideas.

**Comment by forrcaho** [comment]
Paul Batchelor actually suggested we may want to keep our own Soundpipe
sources. Given that I had such a hard time finding them, and as they exist
in AudioKit they don't have their own repo or build files I can see, I
think that might be a good idea. I suggested having it as a submodule just
because that seems to be the way you've organized your repo, but it is
really independent so maybe a submodule would not be appropriate. (The same
goes for Sporth, of course.)

**Comment by fennecdjay** [comment]
I see (I think :smile:).
So the organization should have it's own repo for Soundpipe and Sporth, which would be pointed 
 to by a submodule in their respective plugin repos.
Does this sound correct?

**Comment by forrcaho** [comment]
I'm agnostic on the use of submodules; they seem a bit confusing to me, but
I should probably master them. Your proposal sounds fine to me.
BTW, is there another forum for discussion? This entire email exchange is
getting attached to the original github issue, which just seems a bit
strange for what's now a general and wide-ranging discussion of the project.

**Comment by fennecdjay** [comment]
We should try on the team's page. I had decent discussion with other members there, I hope it'll work for you.
[link](https://github.com/orgs/Gwion/teams/main/discussions/6)

**Comment by femolacaster** [comment]
> **Well, tell us what you think**
I am interested in this project especially in terms of technical documentation and language translation. I have played with JUCE framework before and know a little low-level programming too like C that is being used. And more so, I am a Musician as well.

**Comment by fennecdjay** [comment]
Great! I send you an invite to the organization.
Feel free to ping/mail me for anything.
Hoping to read you soon.
