### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by SamuelMarks** [Gwion/Gwion#234]
**Is your feature request related to a problem? Please describe.**
I can add it if you want. Will probably add it for each of your dependencies first.

**Describe the solution you'd like**
Do you want it?

**Describe alternatives you've considered**
Not providing it.

**Additional context**
Should make a smooth pathway to cross-platform building, testing, and packaging

**Comment by fennecdjay** [comment]
Are you still motivated for this issue @SamuelMarks?
I'm sorry for the delay.
Maybe you could point the PR to some `CMake` branches in the repo not belonging to the gwion org?
I wouldn't merge in their main branch without the owner's agreeing.
But I could make the gwion source point to another branch and merge later when @euppal is ok with it.

**Comment by SamuelMarks** [comment]
Sure I can start sending PRs again. I go down to the lowest dependency, convert that to CMake, then next dependency until the entire project is CMake.

**Comment by SamuelMarks** [comment]
@fennecdjay ?

**Comment by fennecdjay** [comment]
I just merged libprettyerr.
Sorry for the delay, I was quite busy IRL.
What you be the next step?
