### ISSUE TITLE
Windows build flagged as virus by Windows Defender

### ISSUE THREAD

**Issue by avdrd** [Gwion/Gwion#235]
The current build is flagged by Windows 10 Defender as being infected with `Trojan:Win32/Wacatac.B!ml`, specifically in 

```
gwion-nightly-windows-latest-20211216-5b1e28.zip->gwion.exe
```

**Comment by Mafee6** [comment]
[Reddit - Comment - Because its machine learning based, it flags it. see.comment](https://www.reddit.com/r/antivirus/comments/p2o2yj/comment/h8mmdbs/)

**Comment by xerox51** [comment]
I add  <<< "Hello World" >>>; code in a gw file and put the file in the same filepath with gwion.exe on windows10.
Then use gwion command to run the file, nothing output.

**Comment by fennecdjay** [comment]
Did you compiled it or use the release?

**Comment by fennecdjay** [comment]
also, can you try `gwion --help`?
it should output the list of all valid cli arguments.
And what terminal are you using?

**Comment by xerox51** [comment]
> Did you compiled it or use the release?

I use the latest release windows version and use the cmd to run the helloworld code. I also try to run the code in powershell. But nothing output present in the terminal window. Today I download the macOS release version and run the helloworld code normally on macOS. Maybe my windows10 lack of some dynamic link library.

**Comment by fennecdjay** [comment]
I can't really tell for sure as I don't have access to a windows machine at the moment.
I know the release version works in the github CI, as the CI passes and the testing is made on the output.
I'll see if I can get more infos.
Thanks for the report :smile:

**Comment by fennecdjay** [comment]
quick update.
I recall I had gwion working in windows using git bash, maybe that's what the CI is using.
Also for the core of gwion there's only static libraries used, the ones from the submodules

**Comment by xerox51** [comment]
> quick update. I recall I had gwion working in windows using git bash, maybe that's what the CI is using. Also for the core of gwion there's only static libraries used, the ones from the submodules

um, it works normally using git bash on windows. I have try it.

**Comment by fennecdjay** [comment]
Great.
I'll try to improve the windows situation but without a machine running it, it's pretty hard
