### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by bichanna** [Gwion/Gwion#238]
The [link](https://gwion.github.io/Gwion) to the website is dead.

**Comment by fennecdjay** [comment]
it does not seem dead for me?
May be this is due to the latest github outrage?
At nay rate, thanks for reporting :)

**Comment by bichanna** [comment]
Hmm, weird. I tried the link a couple of times, and it didn't respond.
And I'm sure I was connected to the Internet, though.

**Comment by Mafee6** [comment]
Its working now

**Comment by fennecdjay** [comment]
yeah it looks like it was related to the latest github outrage
