### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Gwion/Gwion#257]
I would like to point out that identifiers like “[`_EQUALITY_OPER`](https://github.com/Gwion/Gwion/blob/ae2d0ac56fdddde665e6aaff39cccf7c02686a24/include/import/oper.h#L11 "Update candidate")” and “[`__IMPORT_CHECKER`](https://github.com/Gwion/Gwion/blob/ed766efbb12f27c113f2581956796394f64db46c/include/import/checker.h#L1 "Another update candidate")” [do not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by fennecdjay** [comment]
Sure.
Do you have a suggestion?

**Comment by elfring** [comment]
:thought_balloon: [Affected identifiers](https://en.cppreference.com/w/cpp/language/identifiers#In_declarations "Documentation") can be renamed somehow.

**Comment by elfring** [comment]
:eyes: Please take another look at [name conventions](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?").
