### ISSUE TITLE
ANN and similar macros

### ISSUE THREAD

**Issue by scalarwaves** [Gwion/Gwion#259]
Hello Jérémie,

I am still following the Gwion project and figuring out how I might use it with Rust. I noticed the ANN, ANN2, and ANEW macros are used throughout the code and I'm wondering what these do and if there's a way to translate it into Rust macros/attributes. I'm guesssing that it has to do with the Gwion compiler and memory allocation.

Can you please explain these?

**Comment by fennecdjay** [comment]
sorry for the delay, just saw the issue.
`ANN` is to tell the compiler the arguments can't be `NULL`
`ANN2` is to tell which arguments can't be NULL (used in case  one or more arguments could be)
`ANEW` tells that the function allocates memory.
hope that helps

**Comment by scalarwaves** [comment]
That is helpful, thank you
